file=open("file1","w")
file.write("hello programmer!\n")
file.write("welcome to the world!\n")
file.write("this is Yamini\n")
file.writelines(["Line 1\n", "Line 2\n", "Line 3\n"])
file.close()
file=open("file1","r")
print("read(): ")
read=file.read()
print(read)
file.close()
file=open("file1","r")
print("readline(): ")
readline1=file.readline()
readline2=file.readline()
readline3=file.readline()
print(readline1)
print(readline2)
print(readline3)
file.close()
file=open("file1","r")
print("readlines():")
readlines=file.readlines()
print(readlines)
file.close()
